# Generated by Django 5.2.17 on 2026-08-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('photo', models.ImageField(blank=True, upload_to='cast/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterField(
            model_name='movie',
            name='cast_members',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movies.castmember'),
        ),
    ]
